### PR TITLE
Update example project and add controller usage  and clearing functions

### PR DESCRIPTION
**Pull request by Crucialjun**
Update the example app to be able to run on newer versions,

Add controller parameter to help with clearing and other text management

Added the field clearing feature

### CODE REVIEW

**Comment by deotamaaa** [comment]
this is great update, could you merge it? tia

**Comment by Mastersam07** [comment]
Thanks for your PR @Crucialjun

**Comment by Mastersam07** [comment]
@Crucialjun can you fix the lint issues and update the tests?

See [here](https://github.com/Mastersam07/custom_pin_screen/actions/runs/8741786541/job/24567131056?pr=8)

**Comment by Crucialjun** [comment]
Done

**Comment by Mastersam07** [comment]
@Crucialjun you might want to format locally(run `dart format .`) and ensure there are no lint issues and failing tests then push. See [here](https://github.com/Mastersam07/custom_pin_screen/actions/runs/8943606564/job/24568810866?pr=8).

Apart from that, PR looks good to me.

**Comment by deotamaaa** [comment]
Can you update it to dev.pub, sir? I think the build and pushing to dev.pub are failing, thanks in advance!

**Pull request merged**
