### PR TITLE
New improvements

### PR DESCRIPTION
**Pull request by Crucialjun**
Make on changed mandatory because without it null exception occurs,

Allow key text style customizations

### CODE REVIEW

**Comment by Mastersam07** [comment]
Hi @Crucialjun, 

Thanks for your PR. A couple of things:

1. At this time, we would like to keep the onChanged as a nullable function.
2. The textstyle for the keys looks like a good addition.

With respect to 1 above, the exception on null onChanged has been fixed in #11 and a new version published on pub.dev. You may want to pull the latest changes and update this PR so we can merge it.

**Comment by Crucialjun** [comment]
Try to create the widget without the onchanged and then press any key. It causes a null exception.

**Comment by Mastersam07** [comment]
Hi,

This has been fixed in #11 and a new version with the fix has been published. Please check against the latest and confirm the behaviour.

**Comment by Crucialjun** [comment]
PR updated

**Review by Mastersam07 — APPROVED** [review]
LGTM!

Thanks for all you do.

**Pull request merged**
